name: swc_flutter
description: flutter developement simplifier
version: 1.5.1-nullsafety
homepage: https://github.com/SBNTT/swc_flutter

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ">=5.0.0 <6.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter